# Generated by Django 4.2 on 2023-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0002_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='grade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
